name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "empty233.top"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "empty233.top"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.empty233.top", custom_domain = true },
  { pattern = "quay.empty233.top", custom_domain = true },
  { pattern = "gcr.empty233.top", custom_domain = true },
  { pattern = "k8s-gcr.empty233.top", custom_domain = true },
  { pattern = "k8s.empty233.top", custom_domain = true },
  { pattern = "ghcr.empty233.top", custom_domain = true },
  { pattern = "cloudsmith.empty233.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.empty233.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
